name: adopt_me
description: Adopt animals, dont buy.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - ../assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-SemiBold.ttf
  uses-material-design: true
